name: Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: codeberg-tiny-lazy
    container:
      image: ghcr.io/gohugoio/hugo:v0.164.0@sha256:630fef353bd10c5a23f909002d18dcdc031682375632a38d4fcfd20ad1e5441f
    steps:
      # TODO: Can I replace this dependency on a Shared Action with direct calls to Git?
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Configure Git
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE:-$PWD}"
          git config --global user.name "actions[bot]"
          git config --global user.email "actions[bot]@example.com"

      - name: Build
        run: hugo --minify --gc --cleanDestinationDir --logLevel info

      - name: Deploy
        run: |
          TEMP_DIR=$(mktemp -d)
          cp -R public/. "$TEMP_DIR/"

          git branch -D pages 2>/dev/null || echo "Local pages branch doesn't exist"
          git push origin --delete pages 2>/dev/null || echo "Remote pages branch doesn't exist"

          git checkout --orphan pages

          find . \( -name .git -o -name .gitignore \) -prune -o -exec rm -rf {} + 2>/dev/null || true

          cp -R "$TEMP_DIR"/. .

          rm -rf "$TEMP_DIR"

          git add .
          git commit -m "Deploy site from commit ${{ github.sha }}"

          git push origin pages
